### PR TITLE
Python 3 and PyPy support.

### PR DESCRIPTION
**Pull request by jamadden**
- 100% test coverage.

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]
LGTM

**Comment by mgedmin** [comment]
> Package Index Owner: jw, janjaapdriessen

**Comment by jamadden** [comment]
Thank you! 

A PyPI release would be helpful but isn't currently blocking us.

Pinging @janwijbrand and @janjaapdriessen

(Our PyPI usernames are `mgedmin` and `jamadden` if you're too busy to make a release and don't mind other people doing it.)

**Comment by janjaapdriessen** [comment]
Added `mgedmin` and `jamadden` as owners on pypi. Happy hacking!

**Comment by jamadden** [comment]
Thank you! Released to PyPI.

**Pull request merged**
