### PR TITLE
Rename for better rendering at github.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by mgedmin** [comment]
Why not also rename CHANGES.txt -> CHANGES.rst?

**Comment by mgedmin** [comment]
The failure looks unrelate to the PR.  Probably zc.buildout is broken once again.

Would be a good opportunity to switch to `tox` for more robust testing.

**Comment by jamadden** [comment]
> Probably zc.buildout is broken once again.

I think it is: https://github.com/buildout/buildout/issues/321

**Comment by icemac** [comment]
@mgedmin Pinning to a setuptools version compatible with zc.buildout was easier to implement.

**Comment by mgedmin** [comment]
Does not seem to have worked, though :/

**Comment by mgedmin** [comment]
I've merged the alternative PR that does this.

**Pull request closed without merging**
