### PR TITLE
Resurrection python3. WIP.

### PR DESCRIPTION
**Pull request by janwijbrand**

### CODE REVIEW

**Comment by jamadden** [comment]
zope.errorview 1.0 has already been released to PyPI featuring support for Python 3.

**Comment by janwijbrand** [comment]
Thanks @jamadden  - I didn't notice the Python 3 work was already done and "just" focused on the fact there was still a branch for that. I should've looked better.

**Review by jamadden — COMMENTED** [review]
I don't see very much point to this PR since the applicable changes has already been released. This PR introduces an error in http.py and includes an undesirable file, .coverage, that should never be checked in.

The one useful change I see is updating travis.yml to `pypy` instead of `pypy-5.4.1`. But that should be a separate, simpler, PR.

In general, zopefoundation projects are not maintaining buildout.cfg anymore. Those are often removed.

**Comment by janwijbrand** [comment]
I cleaned up my mistakes anyway. I'll close the PR and delete the branch.

**Comment by jamadden** [comment]
Thanks!

One comment about coverage environments: The emerging pattern used by most zopefoundation projects when we want to have coverage measured by tox.ini, is to use a separate environment that produces a report, and we specify `--fail-under` so that it enforces a constraint. See [zope.publisher](https://github.com/zopefoundation/zope.publisher/blob/master/tox.ini) for a simple example and see [zope.i18n](https://github.com/zopefoundation/zope.i18n/blob/master/tox.ini) for one that also includes the results of running sphinx doctests.

**Comment by janwijbrand** [comment]
Closing this PR - even after cleaning up. Also deleting the branch that was a decoy to me.

**Comment by mgedmin** [comment]
Thank you!

**Pull request closed without merging**
